### ISSUE TITLE
Extract Link (URL, Goto, etc)

### ISSUE THREAD

**Issue by dglunz** [documentcloud/docsplit#127]
I've been trying to find a way to extract the destination URL from a pdf. I know [Poppler has the capability](http://people.freedesktop.org/~aacid/docs/qt4/classPoppler_1_1Link.html) but have yet to figure out where this would come into play.

I'll continue working on figuring this out but if anyone has any advice/can point me in the right direction it'd be greatly appreciated!

**Comment by jogiranjith** [comment]
@dglunz  did u find any solutions . I am looking for the same please let me know . I passed the url of the pdf to split but its throwing back some error.

Errno::ENOENT: No such file or directory @ rb_sysopen

**Comment by dglunz** [comment]
@jogiranjith I don't think I ever found a solution for this. I'm not sure your error is related though. You might want to double check that the path to the pdf you're trying to split is correct. 

`Errno::ENOENT: No such file or directory @ rb_sysopen` is usually caused by an incorrect path.
