### ISSUE TITLE
Can any one please tell me how to pass file path as url to Docsplit ? 

### ISSUE THREAD

**Issue by jogiranjith** [documentcloud/docsplit#138]
I am using s3 to store images . For splitting the documents in to images i need to pass s3 url . Docsplit throws me an error saying the file not found  any help please .

ex:
 Docsplit.extract_images(url,:format => [:jpg])

**Comment by nruth** [comment]
Download a local copy as a tempfile to process, e.g. using something like https://viget.com/extend/make-remote-files-local-with-ruby-tempfile

**Comment by jogiranjith** [comment]
yeah @nruth  thanks i have done it in the same way . 

ex: 
require 'open-uri'
uri = URI.parse(url) 
file = open(uri)
Docsplit.extract_images(file.path,:size => "794x",:format => [:jpg],:output => output_path )
