### ISSUE TITLE
 Couldn't open file '/tmp/docsplit/filename.pdf': No such file or directory.

### ISSUE THREAD

**Issue by luccasmaso** [documentcloud/docsplit#73]
I updated to new docsplit (0.7.2) and I now got this error of no `such file or directory`.

Inside the /tmp folder, I checked for `filename.pdf` and it is there.

Someone can help me what is going on? 

When I'm running the docsplit on a EC2 instance it writes on the root "/tmp" folder and for some reason it does not have permission to read(?) I guess, because in localhost it works.

Thanks!

**Comment by bhushangahire** [comment]
Why its closed do you have a solution for this ?

**Comment by bhushangahire** [comment]
I found the solution its the libreoffice issue. You need to install libreoffice-headless and libreoffice-writer packages

**Comment by thanhtoan1196** [comment]
same issue.
