### ISSUE TITLE
extract_text doesn't work for pdf files with Tesseract

### ISSUE THREAD

**Issue by chintanparikh** [documentcloud/docsplit#86]
Here's what I get when trying to extract the text of a pdf file:

``` ruby
(rdb:5) file_path
"attachments/attachment20130717131653180487.pdf"
(rdb:5) Docsplit.extract_text(file_path, clean: false, output: out)
*** Docsplit::ExtractionFailed Exception: Tesseract Open Source OCR Engine v3.02.02 with Leptonica
Error in pixReadStream: Unknown format: no pix returned
Error in pixRead: pix not read
Unsupported image type.
```

Any ideas?

**Comment by stevesuo** [comment]
I am also having this problem on a Mac with everything installed via Homebrew. Any updates? I found some helpful insights on this error with Tesseract [here](http://kiirani.com/2013/03/22/tesseract-pdf.html). But it would be great to have Docsplit handle the issue internally.
